"""Constants for the Argon Industria OLED integration."""

from __future__ import annotations

from datetime import timedelta

DOMAIN = "argon_industria_oled"

DEFAULT_I2C_BUS = 1
DEFAULT_I2C_ADDRESS = 0x3C

LINE_SOURCE_IP_ADDRESS = "ip_address"
LINE_SOURCE_CPU_TEMPERATURE = "cpu_temperature"
LINE_SOURCE_SENSOR = "sensor"

CONF_LINE1_SOURCE = "line1_source"
CONF_LINE1_SENSOR = "line1_sensor"
CONF_LINE2_SOURCE = "line2_source"
CONF_LINE2_SENSOR = "line2_sensor"

LINE_SOURCES = [
    LINE_SOURCE_IP_ADDRESS,
    LINE_SOURCE_CPU_TEMPERATURE,
    LINE_SOURCE_SENSOR,
]

DEFAULT_LINE1_SOURCE = LINE_SOURCE_IP_ADDRESS
DEFAULT_LINE2_SOURCE = LINE_SOURCE_CPU_TEMPERATURE

DISPLAY_WIDTH = 128
DISPLAY_HEIGHT = 64
DISPLAY_PADDING = 2
MAX_LINE_LENGTH = 18

COORDINATOR_UPDATE_INTERVAL = timedelta(seconds=30)

WELCOME_LINES = ["Argon Industria", "OLED Ready"]

__all__ = [
    "DOMAIN",
    "DEFAULT_I2C_ADDRESS",
    "DEFAULT_I2C_BUS",
    "LINE_SOURCE_IP_ADDRESS",
    "LINE_SOURCE_CPU_TEMPERATURE",
    "LINE_SOURCE_SENSOR",
    "CONF_LINE1_SOURCE",
    "CONF_LINE1_SENSOR",
    "CONF_LINE2_SOURCE",
    "CONF_LINE2_SENSOR",
    "LINE_SOURCES",
    "DEFAULT_LINE1_SOURCE",
    "DEFAULT_LINE2_SOURCE",
    "DISPLAY_WIDTH",
    "DISPLAY_HEIGHT",
    "DISPLAY_PADDING",
    "MAX_LINE_LENGTH",
    "COORDINATOR_UPDATE_INTERVAL",
    "WELCOME_LINES",
]
